import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildChangelogMdx, cleanBody, escapeMdx, isRelease, parseChangelog } from './build-changelog.mjs';

it('parseChangelog splits sections and preserves multiline bodies', () => {
  expect(parseChangelog('# @tallyui/core\n\n## 3.0.0\n\n### Major Changes\n\n- Change\n  continued\n\n## 2.0.0\n- Older\n')).toEqual([
    { version: '3.0.0', body: '\n### Major Changes\n\n- Change\n  continued\n' },
    { version: '2.0.0', body: '- Older\n' },
  ]);
});

it('isRelease accepts only released major.minor.patch versions', () => {
  expect(isRelease('3.0.0')).toBe(true);
  for (const version of ['3.0.0-next.2', 'Unreleased', '3.0', '3.0.0+build']) {
    expect(isRelease(version)).toBe(false);
  }
});

describe('cleanBody', () => {
  it('removes dependency noise and the empty Patch Changes heading', () => {
    expect(cleanBody('\n### Minor Changes\n\n- Feature\n  continued\n\n### Patch Changes\n\n- Updated dependencies [abc1234]\n  - @tallyui/core@3.0.0\n  - @tallyui/database@3.0.0\n')).toBe('### Minor Changes\n\n- Feature\n  continued');
    expect(cleanBody('### Patch Changes\n\n- Updated dependencies\n  - @tallyui/core@3.0.0\n')).toBe('');
    expect(cleanBody('\n \n')).toBe('');
  });

  it('preserves real bullets and their indented content', () => {
    expect(cleanBody('### Patch Changes\n- Updated dependencies [abc1234]\n  - @tallyui/core@3.0.0\n- Fix\n  - @tallyui/core detail\n')).toBe('### Patch Changes\n- Fix\n  - @tallyui/core detail');
    expect(cleanBody('  - Updated dependencies [abc1234]\n    - @tallyui/core@3.0.0\n  - @tallyui/theme is documented')).toBe('  - @tallyui/theme is documented');
  });
});

describe('escapeMdx', () => {
  it('escapes prose but preserves inline code and fenced code', () => {
    const markdown = '{ a } <b> `{ a }`\n\n  ```js\n  { a: "<b>" }\n  ```\n{ after }';
    expect(escapeMdx(markdown)).toBe('\\{ a \\} \\<b> `{ a }`\n\n  ```js\n  { a: "<b>" }\n  ```\n\\{ after \\}');
    expect(escapeMdx('a \\{ b')).toBe('a \\\\\\{ b');
    expect(escapeMdx('`\\{`')).toBe('`\\{`');
  });

  it('matches backtick runs and escapes prose after each span', () => {
    expect(escapeMdx('`` { `a` } <b> `` { after } `{ b }` <end>')).toBe('`` { `a` } <b> `` \\{ after \\} `{ b }` \\<end>');
    expect(escapeMdx('unmatched ` { a }')).toBe('unmatched ` \\{ a \\}');
    expect(escapeMdx('``` { a } ``` { after }')).toBe('``` { a } ``` \\{ after \\}');
  });
});

describe('buildChangelogMdx', () => {
  it('orders released versions numerically and packages in PACKAGE_DIRS order', () => {
    const page = buildChangelogMdx([
      { name: '@tallyui/connector-woocommerce', text: '## 3.0.0\n### Minor Changes\n- Connector' },
      { name: '@tallyui/database', text: '## 10.0.0\n- Ten\n## 9.0.0\n- Nine\n## 3.0.0\n- Database' },
      { name: '@tallyui/core', text: '## Unreleased\n- Future\n## 3.0.0-next.2\n- Preview\n## 3.0.0\n### Major Changes\n- { a }\n## 2.0.0\n- Two' },
      { name: '@tallyui/theme', text: '## 3.0.0\n### Patch Changes\n- Updated dependencies [abc1234]\n  - @tallyui/core@3.0.0' },
      { name: '@tallyui/pos', text: '## 3.0.0\n' },
    ]);
    expect(page.match(/^## .+$/gm)).toEqual(['## 10.0.0', '## 9.0.0', '## 3.0.0', '## 2.0.0']);
    expect(page.match(/^### .+$/gm)).toEqual([
      '### @tallyui/database', '### @tallyui/database', '### @tallyui/core',
      '### @tallyui/database', '### @tallyui/connector-woocommerce', '### @tallyui/core',
    ]);
    expect(page).toContain('### @tallyui/core\n\n#### Major Changes\n- \\{ a \\}');
    expect(page).toContain('#### Minor Changes');
    for (const omitted of ['next.2', 'Unreleased', 'Future', 'Preview', '@tallyui/theme', '@tallyui/pos', 'Updated dependencies']) {
      expect(page).not.toContain(omitted);
    }
    expect(page.startsWith('---\ntitle: Changelog\ndescription: Released changes to the @tallyui packages, newest first.\n---\n\n')).toBe(true);
    expect(page).toContain("{/* Generated by scripts/build-changelog.mjs from each package's CHANGELOG.md. Do not edit: run pnpm changelog:docs after a release. */}\n\n");
    expect(page.endsWith('\n')).toBe(true);
    expect(page.endsWith('\n\n')).toBe(false);
  });
});

it('freshness: the committed changelog page is current', () => {
  expect(() => execFileSync('node', ['scripts/build-changelog.mjs', '--check'], {
    cwd: path.resolve(__dirname, '..'),
  })).not.toThrow();
});
