/**
 * Sample WooCommerce product documents.
 * Shape matches the WooCommerce REST API / RxDB schema.
 */
export const wooSampleProducts = [
  {
    uuid: 'woo-prod-001',
    id: 1,
    name: 'Espresso Machine Pro',
    slug: 'espresso-machine-pro',
    type: 'simple',
    status: 'publish',
    sku: 'ESP-001',
    barcode: '1234567890123',
    price: '599.99',
    regular_price: '599.99',
    sale_price: '',
    on_sale: false,
    description: 'Professional grade espresso machine for commercial use.',
    short_description: 'Pro espresso machine',
    stock_quantity: 15,
    stock_status: 'instock',
    manage_stock: true,
    categories: [{ id: 1, name: 'Equipment', slug: 'equipment' }],
    tags: [{ id: 1, name: 'Coffee', slug: 'coffee' }],
    images: [{ id: 1, src: 'https://picsum.photos/seed/espresso/200', name: 'Espresso Machine', alt: '' }],
    attributes: [],
    variations: [],
    meta_data: [],
    date_modified_gmt: new Date().toISOString(),
  },
  {
    uuid: 'woo-prod-002',
    id: 2,
    name: 'Organic Coffee Beans 1kg',
    slug: 'organic-coffee-beans-1kg',
    type: 'simple',
    status: 'publish',
    sku: 'COF-002',
    barcode: '1234567890124',
    price: '24.99',
    regular_price: '29.99',
    sale_price: '24.99',
    on_sale: true,
    description: 'Single origin organic coffee beans, medium roast.',
    short_description: 'Organic coffee beans',
    stock_quantity: 150,
    stock_status: 'instock',
    manage_stock: true,
    categories: [{ id: 2, name: 'Consumables', slug: 'consumables' }],
    tags: [{ id: 1, name: 'Coffee', slug: 'coffee' }, { id: 2, name: 'Organic', slug: 'organic' }],
    images: [{ id: 2, src: 'https://picsum.photos/seed/coffee/200', name: 'Coffee Beans', alt: '' }],
    attributes: [],
    variations: [],
    meta_data: [],
    date_modified_gmt: new Date().toISOString(),
  },
  {
    uuid: 'woo-prod-003',
    id: 3,
    name: 'Ceramic Mug Set (4 pack)',
    slug: 'ceramic-mug-set-4-pack',
    type: 'simple',
    status: 'publish',
    sku: 'MUG-003',
    barcode: '1234567890125',
    price: '39.99',
    regular_price: '39.99',
    sale_price: '',
    on_sale: false,
    description: 'Set of 4 handcrafted ceramic mugs.',
    short_description: 'Ceramic mug set',
    stock_quantity: 42,
    stock_status: 'instock',
    manage_stock: true,
    categories: [{ id: 3, name: 'Accessories', slug: 'accessories' }],
    tags: [],
    images: [{ id: 3, src: 'https://picsum.photos/seed/mugs/200', name: 'Mug Set', alt: '' }],
    attributes: [],
    variations: [],
    meta_data: [],
    date_modified_gmt: new Date().toISOString(),
  },
];

/**
 * Sample Medusa product documents.
 * Shape matches the Medusa v2 Admin API product shape.
 * Note: `title` not `name`, prices on variants, images use `url` not `src`.
 */
export const medusaSampleProducts = [
  {
    id: 'prod_espresso_01',
    title: 'Commercial Espresso Machine',
    handle: 'commercial-espresso-machine',
    subtitle: null,
    description: 'High-end commercial espresso machine with dual boilers.',
    status: 'published',
    thumbnail: 'https://picsum.photos/seed/medusa-espresso/200',
    is_giftcard: false,
    discountable: true,
    collection_id: null,
    type_id: null,
    external_id: null,
    weight: 15000,
    length: null,
    height: null,
    width: null,
    origin_country: 'IT',
    hs_code: null,
    mid_code: null,
    material: 'Stainless Steel',
    metadata: null,
    categories: [{ id: 'pcat_equip', name: 'Equipment', handle: 'equipment' }],
    tags: [{ id: 'ptag_coffee', value: 'Coffee' }],
    images: [
      { id: 'img_01', url: 'https://picsum.photos/seed/medusa-espresso/200', rank: 0 },
    ],
    options: [],
    variants: [
      {
        id: 'variant_esp_01',
        title: 'Default',
        sku: 'MED-ESP-001',
        barcode: '9876543210001',
        ean: null,
        upc: null,
        allow_backorder: false,
        manage_inventory: true,
        inventory_quantity: 8,
        variant_rank: 0,
        weight: 15000,
        length: null,
        height: null,
        width: null,
        options: [],
        prices: [
          { id: 'price_01', currency_code: 'usd', amount: 89900, min_quantity: null, max_quantity: null },
        ],
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_beans_02',
    title: 'Ethiopian Yirgacheffe Beans',
    handle: 'ethiopian-yirgacheffe-beans',
    subtitle: 'Single Origin',
    description: 'Light roast Ethiopian coffee with floral and citrus notes.',
    status: 'published',
    thumbnail: 'https://picsum.photos/seed/medusa-beans/200',
    is_giftcard: false,
    discountable: true,
    collection_id: null,
    type_id: null,
    external_id: null,
    weight: 1000,
    length: null,
    height: null,
    width: null,
    origin_country: 'ET',
    hs_code: null,
    mid_code: null,
    material: null,
    metadata: null,
    categories: [{ id: 'pcat_beans', name: 'Coffee Beans', handle: 'coffee-beans' }],
    tags: [{ id: 'ptag_coffee', value: 'Coffee' }, { id: 'ptag_single', value: 'Single Origin' }],
    images: [
      { id: 'img_02', url: 'https://picsum.photos/seed/medusa-beans/200', rank: 0 },
    ],
    options: [],
    variants: [
      {
        id: 'variant_beans_01',
        title: '250g',
        sku: 'MED-BEN-250',
        barcode: null,
        ean: null,
        upc: null,
        allow_backorder: false,
        manage_inventory: true,
        inventory_quantity: 200,
        variant_rank: 0,
        weight: 250,
        length: null,
        height: null,
        width: null,
        options: [],
        prices: [
          { id: 'price_02a', currency_code: 'usd', amount: 1899, min_quantity: null, max_quantity: null },
        ],
      },
      {
        id: 'variant_beans_02',
        title: '1kg',
        sku: 'MED-BEN-1K',
        barcode: null,
        ean: null,
        upc: null,
        allow_backorder: false,
        manage_inventory: true,
        inventory_quantity: 85,
        variant_rank: 1,
        weight: 1000,
        length: null,
        height: null,
        width: null,
        options: [],
        prices: [
          { id: 'price_02b', currency_code: 'usd', amount: 5999, min_quantity: null, max_quantity: null },
        ],
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod_grinder_03',
    title: 'Precision Coffee Grinder',
    handle: 'precision-coffee-grinder',
    subtitle: null,
    description: 'Burr grinder with 40 grind settings for pour-over to espresso.',
    status: 'published',
    thumbnail: 'https://picsum.photos/seed/medusa-grinder/200',
    is_giftcard: false,
    discountable: true,
    collection_id: null,
    type_id: null,
    external_id: null,
    weight: 3500,
    length: null,
    height: null,
    width: null,
    origin_country: null,
    hs_code: null,
    mid_code: null,
    material: null,
    metadata: null,
    categories: [{ id: 'pcat_equip', name: 'Equipment', handle: 'equipment' }],
    tags: [],
    images: [
      { id: 'img_03', url: 'https://picsum.photos/seed/medusa-grinder/200', rank: 0 },
    ],
    options: [],
    variants: [
      {
        id: 'variant_grinder_01',
        title: 'Default',
        sku: 'MED-GRN-001',
        barcode: '9876543210003',
        ean: null,
        upc: null,
        allow_backorder: false,
        manage_inventory: true,
        inventory_quantity: 25,
        variant_rank: 0,
        weight: 3500,
        length: null,
        height: null,
        width: null,
        options: [],
        prices: [
          { id: 'price_03', currency_code: 'usd', amount: 24999, min_quantity: null, max_quantity: null },
        ],
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
